export const monedas = [
  { code: "AED", nombre: "Dírham de Emiratos Árabes Unidos (AED)", symbol: "د.إ" },
  { code: "AFN", nombre: "Afgani Afgano (AFN)", symbol: "؋" },
  { code: "ALL", nombre: "Lek Albanés (ALL)", symbol: "L" },
  { code: "AMD", nombre: "Dram Armenio (AMD)", symbol: "֏" },
  { code: "ANG", nombre: "Florín de Antillas Neerlandesas (ANG)", symbol: "ƒ" },
  { code: "AOA", nombre: "Kwanza Angoleño (AOA)", symbol: "Kz" },
  { code: "ARS", nombre: "Pesos Argentinos (ARS)", symbol: "$" },
  { code: "AUD", nombre: "Dólares Australianos (AUD)", symbol: "$" },
  { code: "AWG", nombre: "Florín Arubeño (AWG)", symbol: "ƒ" },
  { code: "AZN", nombre: "Manat Azerbaiyano (AZN)", symbol: "₼" },
  { code: "BAM", nombre: "Marco Convertible Bosnio (BAM)", symbol: "KM" },
  { code: "BBD", nombre: "Dólar Barbadense (BBD)", symbol: "$" },
  { code: "BDT", nombre: "Taka de Bangladés (BDT)", symbol: "৳" },
  { code: "BGN", nombre: "Lev Búlgaro (BGN)", symbol: "лв" },
  { code: "BHD", nombre: "Dinar Bahreiní (BHD)", symbol: "ب.د" },
  { code: "BIF", nombre: "Franco Burundés (BIF)", symbol: "FBu" },
  { code: "BMD", nombre: "Dólar Bermudeño (BMD)", symbol: "$" },
  { code: "BND", nombre: "Dólar de Brunéi (BND)", symbol: "$" },
  { code: "BOB", nombre: "Boliviano (BOB)", symbol: "Bs." },
  { code: "BRL", nombre: "Reales Brasileños (BRL)", symbol: "R$" },
  { code: "BSD", nombre: "Dólar Bahameño (BSD)", symbol: "$" },
  { code: "BTN", nombre: "Ngultrum Butanés (BTN)", symbol: "Nu." },
  { code: "BWP", nombre: "Pula Botsuano (BWP)", symbol: "P" },
  { code: "BYN", nombre: "Rublo Bielorruso (BYN)", symbol: "Br" },
  { code: "BZD", nombre: "Dólar Beliceño (BZD)", symbol: "$" },
  { code: "CAD", nombre: "Dólares Canadienses (CAD)", symbol: "$" },
  { code: "CDF", nombre: "Franco Congoleño (CDF)", symbol: "FC" },
  { code: "CHF", nombre: "Francos Suizos (CHF)", symbol: "CHF" },
  { code: "CLP", nombre: "Pesos Chilenos (CLP)", symbol: "$" },
  { code: "CNY", nombre: "Yuanes Chinos (CNY)", symbol: "¥" },
  { code: "COP", nombre: "Pesos Colombianos (COP)", symbol: "$" },
  { code: "CRC", nombre: "Colón Costarricense (CRC)", symbol: "₡" },
  { code: "CUP", nombre: "Peso Cubano (CUP)", symbol: "$" },
  { code: "CZK", nombre: "Corona Checa (CZK)", symbol: "Kč" },
  { code: "DKK", nombre: "Coronas Danesas (DKK)", symbol: "kr" },
  { code: "DOP", nombre: "Peso Dominicano (DOP)", symbol: "RD$" },
  { code: "DZD", nombre: "Dinar Argelino (DZD)", symbol: "د.ج" },
  { code: "EGP", nombre: "Libra Egipcia (EGP)", symbol: "£" },
  { code: "EUR", nombre: "Euros (EUR)", symbol: "€" },
  { code: "FJD", nombre: "Dólar Fiyiano (FJD)", symbol: "$" },
  { code: "GBP", nombre: "Libras Esterlinas (GBP)", symbol: "£" },
  { code: "GEL", nombre: "Lari Georgiano (GEL)", symbol: "₾" },
  { code: "GHS", nombre: "Cedi Ghanés (GHS)", symbol: "₵" },
  { code: "GTQ", nombre: "Quetzales (GTQ)", symbol: "Q" },
  { code: "GYD", nombre: "Dólar Guyanés (GYD)", symbol: "$" },
  { code: "HKD", nombre: "Dólar de Hong Kong (HKD)", symbol: "$" },
  { code: "HNL", nombre: "Lempira Hondureña (HNL)", symbol: "L" },
  { code: "HRK", nombre: "Kuna Croata (HRK)", symbol: "kn" },
  { code: "HUF", nombre: "Florín Húngaro (HUF)", symbol: "Ft" },
  { code: "IDR", nombre: "Rupia Indonesia (IDR)", symbol: "Rp" },
  { code: "ILS", nombre: "Nuevo Shéquel Israelí (ILS)", symbol: "₪" },
  { code: "INR", nombre: "Rupia India (INR)", symbol: "₹" },
  { code: "ISK", nombre: "Corona Islandesa (ISK)", symbol: "kr" },
  { code: "JMD", nombre: "Dólar Jamaiquino (JMD)", symbol: "$" },
  { code: "JPY", nombre: "Yenes Japoneses (JPY)", symbol: "¥" },
  { code: "KES", nombre: "Chelín Keniano (KES)", symbol: "KSh" },
  { code: "KRW", nombre: "Wones Surcoreanos (KRW)", symbol: "₩" },
  { code: "KZT", nombre: "Tenge Kazajo (KZT)", symbol: "₸" },
  { code: "LAK", nombre: "Kip Laosiano (LAK)", symbol: "₭" },
  { code: "LBP", nombre: "Libra Libanesa (LBP)", symbol: "ل.ل" },
  { code: "LKR", nombre: "Rupia de Sri Lanka (LKR)", symbol: "Rs" },
  { code: "MAD", nombre: "Dírham Marroquí (MAD)", symbol: "د.م." },
  { code: "MDL", nombre: "Leu Moldavo (MDL)", symbol: "L" },
  { code: "MXN", nombre: "Pesos Mexicanos (MXN)", symbol: "$" },
  { code: "MYR", nombre: "Ringgit Malayo (MYR)", symbol: "RM" },
  { code: "NGN", nombre: "Naira Nigeriana (NGN)", symbol: "₦" },
  { code: "NOK", nombre: "Coronas Noruegas (NOK)", symbol: "kr" },
  { code: "NZD", nombre: "Dólares Neozelandeses (NZD)", symbol: "$" },
  { code: "PEN", nombre: "Soles Peruanos (PEN)", symbol: "S/" },
  { code: "PHP", nombre: "Peso Filipino (PHP)", symbol: "₱" },
  { code: "PLN", nombre: "Złoty Polaco (PLN)", symbol: "zł" },
  { code: "RON", nombre: "Leu Rumano (RON)", symbol: "lei" },
  { code: "RUB", nombre: "Rublo Ruso (RUB)", symbol: "₽" },
  { code: "SAR", nombre: "Riyal Saudí (SAR)", symbol: "﷼" },
  { code: "SEK", nombre: "Coronas Suecas (SEK)", symbol: "kr" },
  { code: "SGD", nombre: "Dólar de Singapur (SGD)", symbol: "$" },
  { code: "THB", nombre: "Baht Tailandés (THB)", symbol: "฿" },
  { code: "TRY", nombre: "Lira Turca (TRY)", symbol: "₺" },
  { code: "TWD", nombre: "Dólar Taiwánes (TWD)", symbol: "NT$" },
  { code: "UAH", nombre: "Grivna Ucraniana (UAH)", symbol: "₴" },
  { code: "USD", nombre: "Dólares (USD)", symbol: "$" },
  { code: "UYU", nombre: "Peso Uruguayo (UYU)", symbol: "$" },
  { code: "VND", nombre: "Dong Vietnamita (VND)", symbol: "₫" },
  { code: "ZAR", nombre: "Rand Sudafricano (ZAR)", symbol: "R" }
];
